from selenium.webdriver.common.by import By


class RegistrationForm:
    first_name = (By.ID, 'firstName')
    last_name = (By.ID, 'lastName')
    user_email = (By.ID, 'userEmail')
    gender_checkbox_1 = (By.XPATH, '//*[contains(text(), "Male")]')
    user_mobile_number = (By.ID, 'userNumber')
    data_of_birth = (By.ID, 'dateOfBirthInput')
    subject = (By.ID, "subjectsInput") 
    hobbies_checkbox_1 = (By.XPATH, '//*[contains(text(), "Sports")]')
    picture = (By.ID, 'uploadPicture')
    current_address = (By.ID, 'currentAddress')
    state = (By.ID, 'state')
    select_state = (By.ID, 'state')
    NCR = (By.XPATH, '//*[contains(text(), "NCR")]')
    city = (By.ID, 'city')
    DELHI = (By.XPATH, '//*[contains(text(), "Delhi")]')
    btn_submit = (By.ID, 'submit')
    modal_submitting_form = (By.CSS_SELECTOR, '.modal-body')
    modal_name = (By.XPATH, '(//*[contains(text(), "Student Name")]/../td)[2]')
    modal_email = (By.XPATH, '(//*[contains(text(), "Student Email")]/../td)[2]')
    modal_gender_male = (By.XPATH, '(//*[contains(text(), "Gender")]/../td)[2]')
    modal_mobile_number = (By.XPATH, '(//*[contains(text(), "Mobile")]/../td)[2]')
    modal_subject = (By.XPATH, '(//*[contains(text(), "Subjects")]/../td)[2]')
    modal_date_of_birth = (By.XPATH, '(//*[contains(text(), "Date Of Birth")]/../td)[2]')
    modal_hobbies = (By.XPATH, '(//*[contains(text(), "Hobbies")]/../td)[2]')
    modal_picture = (By.XPATH, '(//*[contains(text(), "Picture")]/../td)[2]')
    modal_current_address = (By.XPATH, '(//*[contains(text(), "Address")]/../td)[2]')